Vet Clinic Database #2: Update table
miltonHenschel/vet-clinic-db pull request #2
Opened 2023-04-12 13:27 UTC by miltonHenschel

- [ ] Use database transactions.

- [ ] Modify and delete data in SQL.

- [ ] Prepare complex queries that answer analytical questions.

- [ ] Take a screenshot of the results of your actions.

-

- [ ] Take a screenshot of the results of your actions.

-

- [ ] Take a screenshot of the results of your queries.

-

- [ ] Take a screenshot of the results of your queries.

-

2023-04-13 07:43 UTC, rloterh reviewed
Hi Henschel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly ensure that all main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
-  Please add the _Key Features_ section of your ReadMe and include 1-3 key features of the project. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-13 15:23 UTC, Lucas-Masaba requested changes
# Hello @miltonHenschel  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Descriptive pull request :scroll: 
- Made changes to README.md :surfer: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 15:23 UTC, Lucas-Masaba commented on queries.sql
> +COMMIT;
- [ ] Please add the SQL code for the queries here as mentioned in the project requirements.
![image](https://user-images.githubusercontent.com/45460192/231805807-ac1caa4b-abcb-4789-8912-f7f7bdb9dd3e.png)

2023-04-13 15:40 UTC, miltonHenschel commented on queries.sql
> +COMMIT;
Thanks @Lucas-Masaba. I forgot to include them. You can see that I already included the screenshots of the resulting queries. Lemme do so ASAP...

2023-04-13 15:53 UTC, afanimartin approved these changes
Hi @miltonHenschel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Changes made as requested

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 15:54 UTC, merged

2023-06-09 12:21 UTC, mikethreels reviewed
Hi Henschel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- good job adding the species
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._